### ISSUE TITLE
Propose an English tutorial to install python 3

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/nemo-template-app#9]
Translating back the French tutorial to English would be a good thing.

Any help is welcome !

**Comment by balmas** [comment]
I will try to do this.

**Comment by PonteIneptique** [comment]
Thanks @balmas :) I have put the French tutorial in there https://github.com/Capitains/nemo-template-app/blob/8fdd3201afa8771173af05572a945427d20aa5fb/docs/python3-fr.md
